title: G-OnRamp
name: gonramp.github.io
description: a collection of informative resources for G-OnRamp, an integrated, web-based graphical interface for performing large scale bioinformatics analyses
